[build]
    publish = "public"
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"
    functions = "netlify/functions/"

[functions]
    node_bundler = "esbuild"
    directory = "netlify/functions/"
